## To modify by developper(s) of the plugin

[plugin-info]
SHORT_PLUGIN_NAME = 'picoquant'  #for instance daqmx
package-url = 'https://github.com/PyMoDAQ/pymodaq_plugins_picoquant' #to modify
description = 'Set of PyMoDAQ plugins for Picoquant instruments (TimeHarp260, ...)'

author = 'SÃ©bastien Weber'
author-email = 'sebastien.weber@cemes.fr'
license = 'MIT'

[plugin-install]
#packages required for your plugin:
packages-required = ['phconvert',
                     'fast_histogram',
                     'bitstring',
                     'pymodaq>=4.0']

[features]  # defines the plugin features contained into this plugin
instruments = true  # true if plugin contains instrument classes (else false, notice the lowercase for toml files)
extensions = false  # true if plugins contains dashboard extensions
pid_models = false  # true if plugins contains pid models
h5exporters = false  # true if plugin contains custom h5 file exporters
scanners = false  # true if plugin contains custom scan layout (daq_scan extensions)

